export const movies = [
  {
    adult: false,
    backdrop_path: "/c6H7Z4u73ir3cIoCteuhJh7UCAR.jpg",
    genre_ids: [28, 12, 14, 878],
    id: 524434,
    original_language: "en",
    original_title: "Eternals",
    overview:
      "The Eternals are a team of ancient aliens who have been living on Earth in secret for thousands of years. When an unexpected tragedy forces them out of the shadows, they are forced to reunite against mankind’s most ancient enemy, the Deviants.",
    popularity: 11902.6,
    poster_path: "/b6qUu00iIIkXX13szFy7d0CyNcg.jpg",
    release_date: "2021-11-03",
    title: "Eternals",
    video: false,
    vote_average: 7.3,
    vote_count: 2748,
  },
  {
    adult: false,
    backdrop_path: "/tutaKitJJIaqZPyMz7rxrhb4Yxm.jpg",
    genre_ids: [16, 35, 10751, 10402],
    id: 438695,
    original_language: "en",
    original_title: "Sing 2",
    overview:
      "Buster and his new cast now have their sights set on debuting a new show at the Crystal Tower Theater in glamorous Redshore City. But with no connections, he and his singers must sneak into the Crystal Entertainment offices, run by the ruthless wolf mogul Jimmy Crystal, where the gang pitches the ridiculous idea of casting the lion rock legend Clay Calloway in their show. Buster must embark on a quest to find the now-isolated Clay and persuade him to return to the stage.",
    popularity: 9205.508,
    poster_path: "/aWeKITRFbbwY8txG5uCj4rMCfSP.jpg",
    release_date: "2021-12-01",
    title: "Sing 2",
    video: false,
    vote_average: 8.3,
    vote_count: 883,
  },
  {
    adult: false,
    backdrop_path: "/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 7827.6,
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 8.4,
    vote_count: 4203,
  },
  {
    adult: false,
    backdrop_path: "/EnDlndEvw6Ptpp8HIwmRcSSNKQ.jpg",
    genre_ids: [35, 14, 12],
    id: 425909,
    original_language: "en",
    original_title: "Ghostbusters: Afterlife",
    overview:
      "When a single mom and her two kids arrive in a small town, they begin to discover their connection to the original Ghostbusters and the secret legacy their grandfather left behind.",
    popularity: 7497.179,
    poster_path: "/sg4xJaufDiQl7caFEskBtQXfD4x.jpg",
    release_date: "2021-11-11",
    title: "Ghostbusters: Afterlife",
    video: false,
    vote_average: 7.6,
    vote_count: 1185,
  },
  {
    adult: false,
    backdrop_path: "/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
    genre_ids: [16, 35, 10751, 14],
    id: 568124,
    original_language: "en",
    original_title: "Encanto",
    overview:
      "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
    popularity: 6462.935,
    poster_path: "/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    release_date: "2021-11-24",
    title: "Encanto",
    video: false,
    vote_average: 7.8,
    vote_count: 2939,
  },
  {
    adult: false,
    backdrop_path: "/o76ZDm8PS9791XiuieNB93UZcRV.jpg",
    genre_ids: [27, 28, 878],
    id: 460458,
    original_language: "en",
    original_title: "Resident Evil: Welcome to Raccoon City",
    overview:
      "Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.",
    popularity: 5472.481,
    poster_path: "/7uRbWOXxpWDMtnsd2PF3clu65jc.jpg",
    release_date: "2021-11-24",
    title: "Resident Evil: Welcome to Raccoon City",
    video: false,
    vote_average: 6.1,
    vote_count: 882,
  },
  {
    adult: false,
    backdrop_path: "/eNI7PtK6DEYgZmHWP9gQNuff8pv.jpg",
    genre_ids: [878, 28, 12],
    id: 624860,
    original_language: "en",
    original_title: "The Matrix Resurrections",
    overview:
      "Plagued by strange memories, Neo's life takes an unexpected turn when he finds himself back inside the Matrix.",
    popularity: 4703.672,
    poster_path: "/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
    release_date: "2021-12-16",
    title: "The Matrix Resurrections",
    video: false,
    vote_average: 6.9,
    vote_count: 2220,
  },
  {
    adult: false,
    backdrop_path: "/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg",
    genre_ids: [878, 28, 12],
    id: 580489,
    original_language: "en",
    original_title: "Venom: Let There Be Carnage",
    overview:
      "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.",
    popularity: 3660.958,
    poster_path: "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg",
    release_date: "2021-09-30",
    title: "Venom: Let There Be Carnage",
    video: false,
    vote_average: 7.1,
    vote_count: 5838,
  },
  {
    adult: false,
    backdrop_path: "/7QabKu8tizoqy8qCZJXljdSpP4A.jpg",
    genre_ids: [16, 10751, 14, 35, 12],
    id: 585083,
    original_language: "en",
    original_title: "Hotel Transylvania: Transformania",
    overview:
      "When Van Helsing's mysterious invention, the \"Monsterfication Ray,\" goes haywire, Drac and his monster pals are all transformed into humans, and Johnny becomes a monster. In their new mismatched bodies, Drac and Johnny must team up and race across the globe to find a cure before it's too late, and before they drive each other crazy.",
    popularity: 3619.893,
    poster_path: "/teCy1egGQa0y8ULJvlrDHQKnxBL.jpg",
    release_date: "2022-01-13",
    title: "Hotel Transylvania: Transformania",
    video: false,
    vote_average: 7.8,
    vote_count: 475,
  },
  {
    adult: false,
    backdrop_path: "/dK12GIdhGP6NPGFssK2Fh265jyr.jpg",
    genre_ids: [28, 35, 80, 53],
    id: 512195,
    original_language: "en",
    original_title: "Red Notice",
    overview:
      "An Interpol-issued Red Notice is a global alert to hunt and capture the world's most wanted. But when a daring heist brings together the FBI's top profiler and two rival criminals, there's no telling what will happen.",
    popularity: 3294.559,
    poster_path: "/lAXONuqg41NwUMuzMiFvicDET9Y.jpg",
    release_date: "2021-11-04",
    title: "Red Notice",
    video: false,
    vote_average: 6.8,
    vote_count: 2669,
  },
  {
    adult: false,
    backdrop_path: "/mo57hzhW3BcZL1f7MNteWKHsmlN.jpg",
    genre_ids: [28, 53],
    id: 763788,
    original_language: "en",
    original_title: "Dangerous",
    overview:
      "A reformed sociopath heads to a remote island after the death of his brother. Soon after his arrival, the island falls under siege from a deadly gang of mercenaries, and when he discovers their role in his brother’s demise, he sets out on a relentless quest for vengeance.",
    popularity: 2695.138,
    poster_path: "/vTtkQGC7qKlSRQJZYtAWAmYdH0A.jpg",
    release_date: "2021-11-05",
    title: "Dangerous",
    video: false,
    vote_average: 6.7,
    vote_count: 108,
  },
  {
    adult: false,
    backdrop_path: "/8jIRAV5KVZeIP6tjI1NuCfb9Il0.jpg",
    genre_ids: [28, 12, 14],
    id: 566525,
    original_language: "en",
    original_title: "Shang-Chi and the Legend of the Ten Rings",
    overview:
      "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.",
    popularity: 2340.652,
    poster_path: "/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg",
    release_date: "2021-09-01",
    title: "Shang-Chi and the Legend of the Ten Rings",
    video: false,
    vote_average: 7.8,
    vote_count: 5154,
  },
  {
    adult: false,
    backdrop_path: "/9fzNf2QcsHVvdx5g5QUOgAWpADw.jpg",
    genre_ids: [18, 27, 9648],
    id: 516329,
    original_language: "en",
    original_title: "Antlers",
    overview:
      "A small-town Oregon teacher and her brother, the local sheriff, discover a young student is harbouring a dangerous secret that could have frightening consequences.",
    popularity: 2079.227,
    poster_path: "/cMch3tiexw3FdOEeZxMWVel61Xg.jpg",
    release_date: "2021-10-28",
    title: "Antlers",
    video: false,
    vote_average: 6.4,
    vote_count: 340,
  },
  {
    adult: false,
    backdrop_path: "/srDyClcl2J0L3ZP9tpahwoTcNxj.jpg",
    genre_ids: [28, 53, 80],
    id: 787310,
    original_language: "en",
    original_title: "Survive the Game",
    overview:
      "When cop David is injured in a drug bust gone wrong, his partner Cal chases the two criminals who shot him. They all land at a remote farm owned by troubled vet Eric, and as Cal and Eric plot their defense, more of the gang arrives - along with a wounded David. Outnumbered, the three heroes must use stealth, smarts, and good shooting to take down the drug-dealing mob.",
    popularity: 2005.829,
    poster_path: "/xF1uc2pEf34X2G41wvZaF5H0V7C.jpg",
    release_date: "2021-10-08",
    title: "Survive the Game",
    video: false,
    vote_average: 6,
    vote_count: 77,
  },
  {
    adult: false,
    backdrop_path: "/1BqX34aJS5J8PefVnQSfQIEPfkl.jpg",
    genre_ids: [80, 28, 53],
    id: 826749,
    original_language: "en",
    original_title: "Fortress",
    overview:
      "The story revolves around a top-secret resort for retired U.S. intelligence officers. A group of criminals led by Balzary breach the compound, hellbent on revenge on Robert, forcing the retired officer and his son to save the day.",
    popularity: 1646.086,
    poster_path: "/vQxtoPJVfpHgL7DCg9hQFZKDWJa.jpg",
    release_date: "2021-12-17",
    title: "Fortress",
    video: false,
    vote_average: 6.3,
    vote_count: 109,
  },
  {
    adult: false,
    backdrop_path: "/yEfU7ahBSJ7OtNWS6WLztdX7YDX.jpg",
    genre_ids: [28, 53],
    id: 860623,
    original_language: "en",
    original_title: "Last Man Down",
    overview:
      "After civilization succumbs to a deadly pandemic and his wife is murdered, a special forces soldier abandons his duty and becomes a hermit in the Nordic wilderness. Years later, a wounded woman appears on his doorstep. She's escaped from a lab and her pursuers believe her blood is the key to a worldwide cure. He's hesitant to get involved, but all doubts are cast aside when he discovers her pursuer is none other than Commander Stone, the man that murdered his wife some years ago.",
    popularity: 1621.215,
    poster_path: "/4B7liCxNCZIZGONmAMkCnxVlZQV.jpg",
    release_date: "2021-10-19",
    title: "Last Man Down",
    video: false,
    vote_average: 7,
    vote_count: 108,
  },
  {
    adult: false,
    backdrop_path: "/xPpXYnCWfjkt3zzE0dpCNME1pXF.jpg",
    genre_ids: [16, 28, 12, 14],
    id: 635302,
    original_language: "ja",
    original_title: "劇場版「鬼滅の刃」無限列車編",
    overview:
      "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!",
    popularity: 1543.985,
    poster_path: "/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg",
    release_date: "2020-10-16",
    title: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train",
    video: false,
    vote_average: 8.4,
    vote_count: 2033,
  },
  {
    adult: false,
    backdrop_path: "/1Wlwnhn5sXUIwlxpJgWszT622PS.jpg",
    genre_ids: [16, 35, 10751],
    id: 585245,
    original_language: "en",
    original_title: "Clifford the Big Red Dog",
    overview:
      "As Emily struggles to fit in at home and at school, she discovers a small red puppy who is destined to become her best friend. When Clifford magically undergoes one heck of a growth spurt, becomes a gigantic dog and attracts the attention of a genetics company, Emily and her Uncle Casey have to fight the forces of greed as they go on the run across New York City. Along the way, Clifford affects the lives of everyone around him and teaches Emily and her uncle the true meaning of acceptance and unconditional love.",
    popularity: 1512.583,
    poster_path: "/oifhfVhUcuDjE61V5bS5dfShQrm.jpg",
    release_date: "2021-11-10",
    title: "Clifford the Big Red Dog",
    video: false,
    vote_average: 7.4,
    vote_count: 880,
  },
  {
    adult: false,
    backdrop_path: "/xGrTm3J0FTafmuQ85vF7ZCw94x6.jpg",
    genre_ids: [18, 36, 12],
    id: 589761,
    original_language: "ru",
    original_title: "Чернобыль",
    overview:
      "The aftermath of a shocking explosion at the Chernobyl nuclear power station made hundreds of people sacrifice their lives to clean up the site of the catastrophe and to successfully prevent an even bigger disaster that could have turned a large part of the European continent into an uninhabitable exclusion zone. This is their story.",
    popularity: 1399.881,
    poster_path: "/AmJLuHjxPdIJO6vmymeWADG6jK5.jpg",
    release_date: "2021-04-15",
    title: "Chernobyl: Abyss",
    video: false,
    vote_average: 6.3,
    vote_count: 267,
  },
  {
    adult: false,
    backdrop_path: "/mRZDHjArYNWpOv06kxRK1cduQKh.jpg",
    genre_ids: [27, 53],
    id: 754934,
    original_language: "en",
    original_title: "Son",
    overview:
      "When a young boy contracts a mysterious illness, his mother must decide how far she will go to protect him from terrifying forces in her past.",
    popularity: 1277.502,
    poster_path: "/4fl6EdtMp6p0RKJgESdFti1J3dC.jpg",
    release_date: "2021-08-06",
    title: "Son",
    video: false,
    vote_average: 6.2,
    vote_count: 67,
  },
  {
    adult: false,
    backdrop_path: "/sLWUtbrpiLp23a0XDSiUiltdFPJ.jpg",
    genre_ids: [28, 12, 14],
    id: 1930,
    original_language: "en",
    original_title: "The Amazing Spider-Man",
    overview:
      "Peter Parker is an outcast high schooler abandoned by his parents as a boy, leaving him to be raised by his Uncle Ben and Aunt May. Like most teenagers, Peter is trying to figure out who he is and how he got to be the person he is today. As Peter discovers a mysterious briefcase that belonged to his father, he begins a quest to understand his parents' disappearance – leading him directly to Oscorp and the lab of Dr. Curt Connors, his father's former partner. As Spider-Man is set on a collision course with Connors' alter ego, The Lizard, Peter will make life-altering choices to use his powers and shape his destiny to become a hero.",
    popularity: 1217.224,
    poster_path: "/fSbqPbqXa7ePo8bcnZYN9AHv6zA.jpg",
    release_date: "2012-06-23",
    title: "The Amazing Spider-Man",
    video: false,
    vote_average: 6.6,
    vote_count: 14278,
  },
  {
    adult: false,
    backdrop_path: "/7h5WAPAcUzOWpp2jrwHBB48790j.jpg",
    genre_ids: [16, 14],
    id: 843241,
    original_language: "ja",
    original_title: "劇場版 七つの大罪 光に呪われし者たち",
    overview:
      'With the help of the "Dragon Sin of Wrath" Meliodas and the worst rebels in history, the Seven Deadly Sins, the "Holy War", in which four races, including Humans, Goddesses, Fairies and Giants fought against the Demons, is finally over. At the cost of the "Lion Sin of Pride" Escanor\'s life, the Demon King was defeated and the world regained peace. After that, each of the Sins take their own path.',
    popularity: 1209.197,
    poster_path: "/k0ThmZQl5nHe4JefC2bXjqtgYp0.jpg",
    release_date: "2021-07-02",
    title: "The Seven Deadly Sins: Cursed by Light",
    video: false,
    vote_average: 8,
    vote_count: 280,
  },
  {
    adult: false,
    backdrop_path: "/weneJTnAb1IFI94SKcaXzBFmPKH.jpg",
    genre_ids: [80, 53, 18, 28],
    id: 818192,
    original_language: "en",
    original_title: "Ida Red",
    overview:
      "Ida Red may not survive her 20-year prison sentence for armed robbery. She turns to her son, Wyatt, for one last job and a chance to regain her freedom.",
    popularity: 1201.235,
    poster_path: "/etMxKseW67499tUJonLNHXTF538.jpg",
    release_date: "2021-11-05",
    title: "Ida Red",
    video: false,
    vote_average: 6,
    vote_count: 20,
  },
  {
    adult: false,
    backdrop_path: "/Aqp47Dbz8f1wnVU1qKvFFXQFROr.jpg",
    genre_ids: [53, 27],
    id: 811072,
    original_language: "es",
    original_title: "Dos",
    overview:
      "Two people, a man and a woman, wake up naked and with their abdomens attached to each other.",
    popularity: 1157.34,
    poster_path: "/5P7QwmoYl70tsRZ8e0VnI9RI1MF.jpg",
    release_date: "2021-07-23",
    title: "Two",
    video: false,
    vote_average: 5.3,
    vote_count: 153,
  },
  {
    adult: false,
    backdrop_path: "/fCdaIDKCIhsorJE30MvfxIlkqrd.jpg",
    genre_ids: [27, 9648, 53],
    id: 646385,
    original_language: "en",
    original_title: "Scream",
    overview:
      "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
    popularity: 1155.714,
    poster_path: "/kZNHR1upJKF3eTzdgl5V8s8a4C3.jpg",
    release_date: "2022-01-12",
    title: "Scream",
    video: false,
    vote_average: 7.2,
    vote_count: 142,
  },
  {
    adult: false,
    backdrop_path: "/g8dafKwLfaueQ5GK0qjKTkRCBAA.jpg",
    genre_ids: [99],
    id: 899082,
    original_language: "en",
    original_title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    overview:
      "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
    popularity: 1097.792,
    poster_path: "/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
    release_date: "2022-01-01",
    title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    video: false,
    vote_average: 8.4,
    vote_count: 747,
  },
  {
    adult: false,
    backdrop_path: "/nvxrQQspxmSblCYDtvDAbVFX8Jt.jpg",
    genre_ids: [35, 18, 878],
    id: 646380,
    original_language: "en",
    original_title: "Don't Look Up",
    overview:
      "Two low-level astronomers must go on a giant media tour to warn humankind of an approaching comet that will destroy planet Earth.",
    popularity: 1093.726,
    poster_path: "/th4E1yqsE8DGpAseLiUrI60Hf8V.jpg",
    release_date: "2021-12-07",
    title: "Don't Look Up",
    video: false,
    vote_average: 7.3,
    vote_count: 3722,
  },
  {
    adult: false,
    backdrop_path: "/mFbS5TwN95BcSEfiztdchLgTQ0v.jpg",
    genre_ids: [18, 36],
    id: 617653,
    original_language: "en",
    original_title: "The Last Duel",
    overview:
      "King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire, Jacques Le Gris, by challenging him to a duel.",
    popularity: 1090.541,
    poster_path: "/zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg",
    release_date: "2021-10-13",
    title: "The Last Duel",
    video: false,
    vote_average: 7.6,
    vote_count: 1449,
  },
  {
    adult: false,
    backdrop_path: "/ezyFE2H7vdFoK3dXK4p4ZUaTukW.jpg",
    genre_ids: [16, 10751, 35],
    id: 823610,
    original_language: "en",
    original_title: "Seal Team",
    overview:
      "After his best friend is killed in a shark attack, Quinn, a lovable yet tenacious seal assembles a SEAL TEAM to fight back against a gang of sharks overtaking the neighborhood. But this merry band of international seals are not at all trained for such a mission. They seek the help of a much more skillful combatant, Claggart, but even his tricks and flips can’t whip these guys into shape. However, with a little bit of ingenuity, intelligence and a lot of heart, our SEAL TEAM may actually be able to bring peace back to their undersea community.",
    popularity: 1048.556,
    poster_path: "/yPZ3I27oeSm4zVesgMxXlhW8GDe.jpg",
    release_date: "2021-10-28",
    title: "Seal Team",
    video: false,
    vote_average: 7,
    vote_count: 78,
  },
  {
    adult: false,
    backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    genre_ids: [878, 12],
    id: 438631,
    original_language: "en",
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    popularity: 1047.726,
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    release_date: "2021-09-15",
    title: "Dune",
    video: false,
    vote_average: 7.9,
    vote_count: 5490,
  },
  {
    adult: false,
    backdrop_path: "/r2GAjd4rNOHJh6i6Y0FntmYuPQW.jpg",
    genre_ids: [12, 28, 53],
    id: 370172,
    original_language: "en",
    original_title: "No Time to Die",
    overview:
      "Bond has left active service and is enjoying a tranquil life in Jamaica. His peace is short-lived when his old friend Felix Leiter from the CIA turns up asking for help. The mission to rescue a kidnapped scientist turns out to be far more treacherous than expected, leading Bond onto the trail of a mysterious villain armed with dangerous new technology.",
    popularity: 1042.804,
    poster_path: "/iUgygt3fscRoKWCV1d0C7FbM9TP.jpg",
    release_date: "2021-09-29",
    title: "No Time to Die",
    video: false,
    vote_average: 7.5,
    vote_count: 3165,
  },
  {
    adult: false,
    backdrop_path: "/7w06baRS9VPm5RYz8lawTCLiR4j.jpg",
    genre_ids: [28, 18, 80],
    id: 592508,
    original_language: "hi",
    original_title: "Sooryavanshi",
    overview:
      "A fearless, faithful albeit slightly forgetful Mumbai cop, Veer Sooryavanshi, the chief of the Anti-Terrorism Squad in India pulls out all the stops and stunts to thwart a major conspiracy to attack his city.",
    popularity: 1033.153,
    poster_path: "/1vuix8r1CJ2M6IldR27Z95hWm7e.jpg",
    release_date: "2021-11-05",
    title: "Sooryavanshi",
    video: false,
    vote_average: 5.9,
    vote_count: 71,
  },
  {
    adult: false,
    backdrop_path: "/zlj0zHo67xXoj7hvwGtaKRkSdBV.jpg",
    genre_ids: [12, 18],
    id: 728526,
    original_language: "en",
    original_title: "Encounter",
    overview:
      "A decorated Marine goes on a rescue mission to save his two young sons from an unhuman threat. As their journey takes them in increasingly dangerous directions, the boys will need to leave their childhoods behind.",
    popularity: 1004.931,
    poster_path: "/tUkY0WxffPZ9PoyC62PIyyUMGnt.jpg",
    release_date: "2021-12-03",
    title: "Encounter",
    video: false,
    vote_average: 6.3,
    vote_count: 198,
  },
  {
    adult: false,
    backdrop_path: "/oE6bhqqVFyIECtBzqIuvh6JdaB5.jpg",
    genre_ids: [878, 18, 12],
    id: 522402,
    original_language: "en",
    original_title: "Finch",
    overview:
      "On a post-apocalyptic Earth, a robot, built to protect the life of his dying creator's beloved dog, learns about life, love, friendship, and what it means to be human.",
    popularity: 984.566,
    poster_path: "/jKuDyqx7jrjiR9cDzB5pxzhJAdv.jpg",
    release_date: "2021-11-04",
    title: "Finch",
    video: false,
    vote_average: 8.1,
    vote_count: 1778,
  },
  {
    adult: false,
    backdrop_path: "/tTlAA0REGPXSZPBfWyTW9ipIv1I.jpg",
    genre_ids: [28, 12, 878, 18],
    id: 315635,
    original_language: "en",
    original_title: "Spider-Man: Homecoming",
    overview:
      "Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
    popularity: 947.032,
    poster_path: "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
    release_date: "2017-07-05",
    title: "Spider-Man: Homecoming",
    video: false,
    vote_average: 7.4,
    vote_count: 17837,
  },
  {
    adult: false,
    backdrop_path: "/4EJSMQOM1bZPHvzqAQe87suBxdf.jpg",
    genre_ids: [10752, 36, 18],
    id: 885110,
    original_language: "en",
    original_title: "Amina",
    overview:
      "In 16th-century Zazzau, now Zaria, Nigeria, Amina must utilize her military skills and tactics to defend her family's kingdom. Based on a true story.",
    popularity: 933.341,
    poster_path: "/gII53HAH7UA1yx189vROMzWA5ib.jpg",
    release_date: "2021-11-04",
    title: "Amina",
    video: false,
    vote_average: 6.5,
    vote_count: 66,
  },
  {
    adult: false,
    backdrop_path: "/u7SeO6Y42P7VCTWLhpnL96cyOqd.jpg",
    genre_ids: [28, 12, 14],
    id: 102382,
    original_language: "en",
    original_title: "The Amazing Spider-Man 2",
    overview:
      "For Peter Parker, life is busy. Between taking out the bad guys as Spider-Man and spending time with the person he loves, Gwen Stacy, high school graduation cannot come quickly enough. Peter has not forgotten about the promise he made to Gwen’s father to protect her by staying away, but that is a promise he cannot keep. Things will change for Peter when a new villain, Electro, emerges, an old friend, Harry Osborn, returns, and Peter uncovers new clues about his past.",
    popularity: 930.086,
    poster_path: "/c3e9e18SSlvFd1cQaGmUj5tqL5P.jpg",
    release_date: "2014-04-16",
    title: "The Amazing Spider-Man 2",
    video: false,
    vote_average: 6.5,
    vote_count: 10489,
  },
  {
    adult: false,
    backdrop_path: "/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg",
    genre_ids: [35, 28, 12, 878],
    id: 550988,
    original_language: "en",
    original_title: "Free Guy",
    overview:
      "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.",
    popularity: 907.093,
    poster_path: "/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg",
    release_date: "2021-08-11",
    title: "Free Guy",
    video: false,
    vote_average: 7.7,
    vote_count: 4596,
  },
  {
    adult: false,
    backdrop_path: "/AmLpWYm9R3Ur2FLPgj5CH3wR8wp.jpg",
    genre_ids: [878, 53],
    id: 739413,
    original_language: "en",
    original_title: "Mother/Android",
    overview:
      "Georgia and her boyfriend Sam go on a treacherous journey to escape their country, which is caught in an unexpected war with artificial intelligence. Days away from the arrival of their first child, the couple must face No Man’s Land—a stronghold of the android uprising—in hopes of reaching safety before giving birth.",
    popularity: 899.874,
    poster_path: "/rO3nV9d1wzHEWsC7xgwxotjZQpM.jpg",
    release_date: "2021-12-17",
    title: "Mother/Android",
    video: false,
    vote_average: 6,
    vote_count: 255,
  },
  {
    adult: false,
    backdrop_path: "/sdL37sfUBth7mdkAolI83bXAl7L.jpg",
    genre_ids: [16, 878, 10751, 35],
    id: 482321,
    original_language: "en",
    original_title: "Ron's Gone Wrong",
    overview:
      "In a world where walking, talking, digitally connected bots have become children's best friends, an 11-year-old finds that his robot buddy doesn't quite work the same as the others do.",
    popularity: 895.119,
    poster_path: "/7M0uwPgwvPONdFG0jk8TPK09xJU.jpg",
    release_date: "2021-10-15",
    title: "Ron's Gone Wrong",
    video: false,
    vote_average: 8.3,
    vote_count: 711,
  },
  {
    adult: false,
    backdrop_path: "/5B22eed7ErxFiYAG4Ksb4eLwKNF.jpg",
    genre_ids: [16, 10751, 12, 35],
    id: 770254,
    original_language: "en",
    original_title: "Back to the Outback",
    overview:
      "Tired of being locked in a reptile house where humans gawk at them like they are monsters, a ragtag group of Australia’s deadliest creatures plot an escape from their zoo to the Outback, a place where they’ll fit in without being judged.",
    popularity: 882.092,
    poster_path: "/zNXNRLH5wJprUG6B1olaBTNZOjy.jpg",
    release_date: "2021-12-03",
    title: "Back to the Outback",
    video: false,
    vote_average: 7.8,
    vote_count: 243,
  },
  {
    adult: false,
    backdrop_path: "/x78cvxbmpBNcHON7x3Iv8vih5Sj.jpg",
    genre_ids: [16, 35, 10751],
    id: 774741,
    original_language: "en",
    original_title: "Diary of a Wimpy Kid",
    overview:
      "Greg Heffley is a scrawny but ambitious kid with an active imagination and big plans to be rich and famous – he just has to survive middle school first.",
    popularity: 880.85,
    poster_path: "/4vIffNcdZfqTR7IWi0eOljbxesU.jpg",
    release_date: "2021-12-03",
    title: "Diary of a Wimpy Kid",
    video: false,
    vote_average: 6.8,
    vote_count: 137,
  },
  {
    adult: false,
    backdrop_path: "/kGyl8SCp9We2eTjRydqjJQJ18tg.jpg",
    genre_ids: [80, 18, 53],
    id: 656991,
    original_language: "en",
    original_title: "Wild Indian",
    overview:
      "Decades after covering up his classmate’s murder, Michael has moved on from his reservation and fractured past. When a man who shares his violent secret seeks vengeance, Michael goes to great lengths to protect his new life with his wife and boss from the demons of his past.",
    popularity: 861.413,
    poster_path: "/yhOpkNvgW1ZzmEpR4iqxKwKKShL.jpg",
    release_date: "2021-09-03",
    title: "Wild Indian",
    video: false,
    vote_average: 6.5,
    vote_count: 12,
  },
  {
    adult: false,
    backdrop_path: "/kJ2srEZSlmGfAqLKGVMPhBDdr1G.jpg",
    genre_ids: [10770, 53, 80],
    id: 831223,
    original_language: "en",
    original_title: "Gone Mom: The Disappearance of Jennifer Dulos",
    overview:
      "Jennifer Dulos, the wealthy, Connecticut mother-of-five who mysteriously vanished.",
    popularity: 840.942,
    poster_path: "/mzTNGnLG6LTHmrqrY0IADHDuyOJ.jpg",
    release_date: "2021-06-05",
    title: "Gone Mom: The Disappearance of Jennifer Dulos",
    video: false,
    vote_average: 7.8,
    vote_count: 55,
  },
  {
    adult: false,
    backdrop_path: "/gGTCDNEvwG848u34Op1nZNALLUr.jpg",
    genre_ids: [28, 80, 53, 12],
    id: 385128,
    original_language: "en",
    original_title: "F9",
    overview:
      "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
    popularity: 833.323,
    poster_path: "/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
    release_date: "2021-05-19",
    title: "F9",
    video: false,
    vote_average: 7.4,
    vote_count: 4814,
  },
  {
    adult: false,
    backdrop_path: "/ng6SSB3JhbcpKTwbPDsRwUYK8Cq.jpg",
    genre_ids: [28, 12, 878],
    id: 429617,
    original_language: "en",
    original_title: "Spider-Man: Far From Home",
    overview:
      "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
    popularity: 820.262,
    poster_path: "/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg",
    release_date: "2019-06-28",
    title: "Spider-Man: Far From Home",
    video: false,
    vote_average: 7.5,
    vote_count: 11780,
  },
  {
    adult: false,
    backdrop_path: "/pxOiKwRvNp3zFOiuwpYpzlbmEgC.jpg",
    genre_ids: [16, 35, 12, 10751],
    id: 459151,
    original_language: "en",
    original_title: "The Boss Baby: Family Business",
    overview:
      "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",
    popularity: 814.893,
    poster_path: "/kv2Qk9MKFFQo4WQPaYta599HkJP.jpg",
    release_date: "2021-07-01",
    title: "The Boss Baby: Family Business",
    video: false,
    vote_average: 7.6,
    vote_count: 1702,
  },
  {
    adult: false,
    backdrop_path: "/uWGPC7j70LE64nbetxQGSSYJO53.jpg",
    genre_ids: [53, 10752],
    id: 762433,
    original_language: "en",
    original_title: "Zeros and Ones",
    overview:
      "Called to Rome to stop an imminent terrorist bombing, a soldier desperately seeks news of his imprisoned brother — a rebel with knowledge that could thwart the attack. Navigating the capital's darkened streets, he races to a series of ominous encounters to keep the Vatican from being blown to bits.",
    popularity: 793.543,
    poster_path: "/sopFsYj2yaKXVsBRVAPcNlqTLY5.jpg",
    release_date: "2021-11-18",
    title: "Zeros and Ones",
    video: false,
    vote_average: 5.5,
    vote_count: 101,
  },
  {
    adult: false,
    backdrop_path: "/qOnLuCJDFhRzbWzhpA4aoK75vfY.jpg",
    genre_ids: [27, 878, 18, 53],
    id: 523936,
    original_language: "fr",
    original_title: "Méandre",
    overview:
      "After getting a car ride from an unknown man, Lisa wakes up in a tube. On her arm is strapped a bracelet with a countdown. She quickly understands that every 8 minutes, fire burns an occupied section. She has no choice but to crawl into safe sections to survive. To know why she’s there and how to get out, Lisa will have to face the memories of her dead daughter…",
    popularity: 789.652,
    poster_path: "/2OTIAx8AmwGCaXmq5ohQCyPUjdC.jpg",
    release_date: "2021-05-26",
    title: "Meander",
    video: false,
    vote_average: 6,
    vote_count: 188,
  },
  {
    adult: false,
    backdrop_path: "/39EQTf94Lckdo8yzS1CdWQSgmen.jpg",
    genre_ids: [27, 9648, 53],
    id: 609972,
    original_language: "en",
    original_title: "Paranormal Activity: Next of Kin",
    overview:
      "Margot, a documentary filmmaker, heads to a secluded Amish community in the hopes of learning about her long-lost mother and extended family. Following a string of strange occurrences and discoveries, she comes to realize this community may not be what it seems.",
    popularity: 778.818,
    poster_path: "/bXAVveHiLotZbWdg3PKGhAzxYKP.jpg",
    release_date: "2021-10-29",
    title: "Paranormal Activity: Next of Kin",
    video: false,
    vote_average: 6.7,
    vote_count: 198,
  },
  {
    adult: false,
    backdrop_path: "/sWvxBXNtCOaGdtpKNLiOqmwb10N.jpg",
    genre_ids: [14, 28],
    id: 557,
    original_language: "en",
    original_title: "Spider-Man",
    overview:
      "After being bitten by a genetically altered spider at Oscorp, nerdy but endearing high school student Peter Parker is endowed with amazing powers to become the superhero known as Spider-Man.",
    popularity: 772.888,
    poster_path: "/gh4cZbhZxyTbgxQPxD0dOudNPTn.jpg",
    release_date: "2002-05-01",
    title: "Spider-Man",
    video: false,
    vote_average: 7.2,
    vote_count: 15041,
  },
  {
    adult: false,
    backdrop_path: "/hAv1GwwatyWV1RFXOfaASxgUVm4.jpg",
    genre_ids: [28, 12, 35],
    id: 657644,
    original_language: "ml",
    original_title: "മിന്നൽ മുരളി",
    overview:
      "A tailor gains special powers after being struck by lightning but must take down an unexpected foe if he is to become the superhero his hometown in Kerala needs.",
    popularity: 763.862,
    poster_path: "/efetKFDyptrRpoHBb103Tg3Auw5.jpg",
    release_date: "2021-12-24",
    title: "Minnal Murali",
    video: false,
    vote_average: 7.2,
    vote_count: 137,
  },
  {
    adult: false,
    backdrop_path: "/1zgob2Z8xVE3RZUgOKnHKcVPzOE.jpg",
    genre_ids: [16, 35, 14],
    id: 877183,
    original_language: "en",
    original_title: "The Simpsons in Plusaversary",
    overview:
      "The Simpsons host a Disney+ Day party and everyone is on the list… except Homer. With friends from across the service and music fit for a Disney Princess, Plusaversary is Springfield's event of the year.",
    popularity: 763.739,
    poster_path: "/p5jzbffrXuBTjsiwrQ3aOMTrvCj.jpg",
    release_date: "2021-11-12",
    title: "The Simpsons in Plusaversary",
    video: false,
    vote_average: 6.6,
    vote_count: 208,
  },
  {
    adult: false,
    backdrop_path: "/upOi9aVqPPky7Ba4GsiyFdjc82I.jpg",
    genre_ids: [37, 28, 53],
    id: 887767,
    original_language: "fr",
    original_title: "Last Shoot Out",
    overview:
      "Soon after a newlywed learns that her husband had her father shot down, she flees from the Callahan ranch in fear. She's rescued by a gunman who safeguards her at a remote outpost as he staves off her husband's attempts to reclaim his bride.",
    popularity: 757.332,
    poster_path: "/pvEtPxotI3POlVPvNxgrHJuDXfe.jpg",
    release_date: "2021-12-03",
    title: "Last Shoot Out",
    video: false,
    vote_average: 6.3,
    vote_count: 67,
  },
  {
    adult: false,
    backdrop_path: "/4gKxQIW91hOTELjY5lzjMbLoGxB.jpg",
    genre_ids: [28, 53, 878],
    id: 763164,
    original_language: "en",
    original_title: "Apex",
    overview:
      "Ex-cop Thomas Malone is serving a life sentence for a crime he didn’t commit. He is offered a chance at freedom if he can survive a deadly game of Apex, in which six hunters pay for the pleasure of hunting another human on a remote island. He accepts, and once he arrives, all hell breaks loose.",
    popularity: 745.763,
    poster_path: "/chTkFGToW5bsyw3hgLAe4S5Gt3.jpg",
    release_date: "2021-11-12",
    title: "Apex",
    video: false,
    vote_average: 5.5,
    vote_count: 336,
  },
  {
    adult: false,
    backdrop_path: "/poLzOfMBc2S4AroQPtzlaPRdEwn.jpg",
    genre_ids: [10749, 18],
    id: 763148,
    original_language: "en",
    original_title: "Time Is Up",
    overview:
      "Vivien, an accomplished student with a passion for physics, and Roy, a troubled young man, are involved in an accident that forces them to reclaim their lives one minute at the time.",
    popularity: 740.701,
    poster_path: "/dxWHyMY4HoXH8LiEhYlga2OtK5B.jpg",
    release_date: "2021-09-09",
    title: "Time Is Up",
    video: false,
    vote_average: 6.6,
    vote_count: 145,
  },
  {
    adult: false,
    backdrop_path: "/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg",
    genre_ids: [28, 12, 14],
    id: 436969,
    original_language: "en",
    original_title: "The Suicide Squad",
    overview:
      "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
    popularity: 732.488,
    poster_path: "/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg",
    release_date: "2021-07-28",
    title: "The Suicide Squad",
    video: false,
    vote_average: 7.7,
    vote_count: 5291,
  },
  {
    adult: false,
    backdrop_path: "/lV3UFPPxDIPelh46G9oySXN9Mcz.jpg",
    genre_ids: [10749, 18],
    id: 744275,
    original_language: "en",
    original_title: "After We Fell",
    overview:
      "Just as Tessa's life begins to become unglued, nothing is what she thought it would be. Not her friends nor her family. The only person that she should be able to rely on is Hardin, who is furious when he discovers the massive secret that she's been keeping. Before Tessa makes the biggest decision of her life, everything changes because of revelations about her family.",
    popularity: 723.461,
    poster_path: "/dU4HfnTEJDf9KvxGS9hgO7BVeju.jpg",
    release_date: "2021-09-01",
    title: "After We Fell",
    video: false,
    vote_average: 7.2,
    vote_count: 1341,
  },
  {
    adult: false,
    backdrop_path: "/dIibeeq4QMay5bTJ2vjr72IFFRo.jpg",
    genre_ids: [14, 12, 35],
    id: 589754,
    original_language: "ru",
    original_title: "Последний богатырь: Корень зла",
    overview:
      "Peace and tranquility have set in Belogorie. The evil was defeated and Ivan is now enjoying his well-deserved fame. He is surrounded by his family, friends and small wonders from the modern world that help him lead a comfortable life. Luckily, he has his Magic Sword to cut a gap between the worlds to get some supplies quite regularly. But when an ancient evil rises and the existence of the magic world is put to danger, Ivan has to team up with his old friends and his new rivals. They will set out on a long journey beyond the known world to find a way to defeat the enemies and to return peace to Belogorie.",
    popularity: 716.959,
    poster_path: "/5VJSIAhSn4qUsg5nOj4MhQhF5wQ.jpg",
    release_date: "2020-12-31",
    title: "The Last Warrior: Root of Evil",
    video: false,
    vote_average: 7,
    vote_count: 78,
  },
  {
    adult: false,
    backdrop_path: "/lch8GEMczkpRabis40Uhw8zkVA9.jpg",
    genre_ids: [27],
    id: 611651,
    original_language: "en",
    original_title: "Sator",
    overview:
      "Secluded in a desolate forest, a broken family is observed by Sator, a supernatural entity who is attempting to claim them.",
    popularity: 716.17,
    poster_path: "/p0OgWKpcRYboZOmuozorfvQt0qL.jpg",
    release_date: "2021-09-30",
    title: "Sator",
    video: false,
    vote_average: 6.4,
    vote_count: 7,
  },
];
